## Reviewing Python Concepts - Part 2

## Contents

* Conditional loop statement
    * While logical condition
    * Loop control

* Iterative loop statement
    * For loop
    * Integer Sequences

* Display statement
    * Formatting
* Input statement
    * `input` statement always returns a string

* Generic operations on containers

* Operations on list
* Operations on dictionary
* Operations on set
`-> Done`

* Operations on strings

* Files 

* Function Definition
    * function calls

* Class Definition

## Conditional loop statement

In [2]:
i = 0
s = 0
while i <= 10:
    # i = i + 1
    s = s + i ** 2
    i +=1
    break
print(s)

385


In [11]:
list_a = "A B C D E F G H".split()

for ind, item in enumerate(list_a):
    # ind = ind + 1
    # item = item.lower()
    # print("Index:" ,ind, "item:", item) # similar C
    # print(f"Index: {ind + 1} item: {item.lower()}")
    print("Index: {} item: {}".format(ind + 1, item.lower()))

Index: 1 item: a
Index: 2 item: b
Index: 3 item: c
Index: 4 item: d
Index: 5 item: e
Index: 6 item: f
Index: 7 item: g
Index: 8 item: h


## Formatting with `f` string

In [14]:
import random 
s = random.randint(0,100) / 3
print(f"{s:.2f}")

29.00


In [17]:
n = 200.68888
f"This is a comment for {n:.2f}"

'This is a comment for 200.69'

## Parameters of `print()`

In [22]:
x = 10
y = 20
print("v=", 3, "cm :", x, ",", y+4, sep="...", end=" + ")
print("This is a comment")

v=...3...cm :...10...,...24 + This is a comment


## Generic operation on containers

In [23]:
list_a = "A B C D E F G H".split()
len(list_a)

8

In [8]:
import numpy as np
num_array = np.array([[1, 2, 3, 4, 5, 6],
                     [6, 2, 3, 4, 5, 6]])
num_array

array([[1, 2, 3, 4, 5, 6],
       [6, 2, 3, 4, 5, 6]])

In [9]:
num_array.shape

(2, 6)

In [16]:
# min max sum
np.min(num_array, axis=1)

array([1, 2])

In [3]:
np.max(num_array)

6

In [4]:
np.var(num_array)

2.9166666666666665

In [18]:
np.mean(num_array, axis=1)

array([3.5       , 4.33333333])

In [20]:
a_list = "B C A D F G E".split()
sorted(a_list)

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [21]:
a_list = "B C A D F G E".split()
b_list = [1, 2, 3, 4, 5, 6, 7]

for a_item, b_item in zip(a_list, b_list):
    print(a_item, b_item)

B 1
C 2
A 3
D 4
F 5
G 6
E 7


## Class

### Class Basic

In [1]:
class Dog:
    """Dog class example"""
    kind = 'canine'  # Class variable shared by all instances.

    def __init__(self, name):
        self.name = name  # Instance variable unique to each instance.

fido = Dog('Fido')
buddy = Dog('Buddy')

In [2]:
# Shared by all dogs.
assert fido.kind == 'canine'
assert buddy.kind == 'canine'

In [5]:
fido.name

'Fido'

In [6]:
buddy.name

'Buddy'

### Shared data DO and DONT

In [7]:
class DogWithSharedTricks:
    """Dog class example with wrong shared variable usage"""
    tricks = []  # Mistaken use of a class variable (see below) for mutable objects.

    def __init__(self, name):
        self.name = name  # Instance variable unique to each instance.

    def add_trick(self, trick):
        """Add trick to the dog

        This function illustrate mistaken use of mutable class variable tricks (see below).
        """
        self.tricks.append(trick)

fido = DogWithSharedTricks('Fido')
buddy = DogWithSharedTricks('Buddy')

fido.add_trick('roll over')
buddy.add_trick('play dead')

In [9]:
fido.tricks

['roll over', 'play dead']

In [10]:
buddy.tricks

['roll over', 'play dead']

In [11]:
class DogWithTricks:
    """Dog class example"""

    def __init__(self, name):
        self.name = name  # Instance variable unique to each instance.
        self.tricks = []  # creates a new empty list for each dog

    def add_trick(self, trick):
        """Add trick to the dog

        This function illustrate a correct use of mutable class variable tricks (see below).
        """
        self.tricks.append(trick)

fido = DogWithTricks('Fido')
buddy = DogWithTricks('Buddy')

fido.add_trick('roll over')
buddy.add_trick('play dead')

In [12]:
fido.tricks

['roll over']

In [13]:
buddy.tricks

['play dead']

### Special method of Class

In [24]:
class Vector:
    
    def __init__(self, x, y) -> None:
        self.x = x
        self.y = y
        
    def __add__(self, other):
        return Vector(self.x + other.x, self.y + other.y)
    
    def __repr__(self) -> str:
        return f"({self.x}, {self.y})"
        

v1 = Vector(1, 2)
v2 = Vector(10, 20) 
    

In [25]:
v3 = v1+ v2

In [26]:
v3

(11, 22)